name: Feature Request
description: Suggest a new feature
title: "Feature: "
labels: ["feature"]
assignees: []

body:
  - type: input
    id: contact_name
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: "ex. Sertha Taweewattana"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: dropdown
    id: request_type
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New Feature
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: What is the OS which you want to suggest?
      description: Select the operating system
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: feature_details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what you want
      placeholder: "Feature details!"
    validations:
      required: true
